chain_type: simple
generator: 
  models:
    open_source_model: "accounts/fireworks/models/mistral-7b-instruct-4k"
    open_ai_model: "gpt-3.5-turbo"
    hugging_face_model: "tiiuae/falcon-7b-instruct"

  model_config:
    max_tokens: 256
    temperature: 0.7

  prompt_template:
    domain: "Life Science"
    prompt_type: custom  #["general", "specific","custom"] 



  